file_location="C:/Users/lavee/Documents/Semester_1/MWDB/Project/Phase1/Final/Programs/"
user_file_name="desctxt/desctxt/devset_textTermsPerUser.txt"
image_file_name="desctxt/desctxt/devset_textTermsPerImage.txt"
location_file_name="desctxt/desctxt/devset_textTermsPerPOI.txt"
parsed_location_file_name="location_text_parsed.csv"
xml_file_loc="C:/Users/lavee/Documents/Semester_1/MWDB/Project/Phase1/Final/Programs/"
xml_file_name="devset_topics.xml"
visual_desc_location="C:/Users/lavee/Documents/Semester_1/MWDB/Project/Phase1/Final/Programs/descvis/descvis/img/"